class Theater < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'TOHOシネマズ池袋' },
    { id: 3, name: 'グランドシネマサンシャイン' },
    { id: 4, name: '池袋HUMAXシネマズ' },
    { id: 5, name: '池袋シネマ・ロサ' },
    { id: 6, name: 'シネ・リーブル池袋' },
    { id: 7, name: '新文芸坐' },
    { id: 8, name: 'TOHOシネマズ新宿' },
    { id: 9, name: '新宿ピカデリー' },
    { id: 10, name: '新宿バルト9' },
    { id: 11, name: '109シネマズプレミアム新宿' },
    { id: 12, name: '新宿武蔵野館' },
    { id: 13, name: '新宿シネマカリテ' },
    { id: 14, name: 'シネマート新宿' },
    { id: 15, name: 'kino cinema新宿' },
    { id: 16, name: 'テアトル新宿' },
    { id: 17, name: "K's cinema" },
    { id: 18, name: '早稲田松竹' },
    { id: 19, name: 'TOHOシネマズ渋谷' },
    { id: 20, name: 'ユーロスペース' },
    { id: 21, name: 'シアター・イメージフォーラム' },
    { id: 22, name: 'Bunkamuraル・シネマ 渋谷宮下' },
    { id: 23, name: 'WHITE CINE QUINTO' },
    { id: 24, name: 'シネマヴェーラ渋谷' },
    { id: 25, name: 'ヒューマントラストシネマ渋谷' },
    { id: 26, name: '渋谷HUMAXシネマ' },
    { id: 27, name: '渋谷シネクイント' },
    { id: 28, name: 'YEBISU GARDEN CINEMA' },
    { id: 29, name: '東京都写真美術館ホール' },
    { id: 30, name: '109シネマズ二子玉川' },
    { id: 31, name: '目黒シネマ' },
    { id: 32, name: '下北沢トリウッド' },
    { id: 33, name: 'シモキタ-エキマエ-シネマ K2' },
    { id: 34, name: '下高井戸シネマ' },
    { id: 35, name: 'TOHOシネマズ日比谷' },
    { id: 36, name: 'TOHOシネマズシャンテ' },
    { id: 37, name: '丸の内ピカデリー' },
    { id: 38, name: 'シネスイッチ銀座' },
    { id: 39, name: 'ヒューマントラストシネマ有楽町' },
    { id: 40, name: '角川シネマ有楽町' },
    { id: 41, name: '丸の内TOEI' },
    { id: 42, name: '東劇' },
    { id: 43, name: 'TOHOシネマズ日本橋' },
    { id: 44, name: '国立映画アーカイブ' },
    { id: 45, name: 'TOHOシネマズ六本木ヒルズ' },
    { id: 46, name: 'T・ジョイPRINCE品川' },
    { id: 47, name: '神保町シアター' },
    { id: 48, name: 'アテネ・フランセ文化センター' },
    { id: 49, name: 'TOHOシネマズ上野' },
    { id: 50, name: 'TOHOシネマズ錦糸町（オリナス）' },
    { id: 51, name: 'TOHOシネマズ錦糸町（楽天地）' },
    { id: 52, name: 'Stranger' },
    { id: 53, name: 'CINEMA Chupki TABATA' },
    { id: 54, name: 'キネカ大森' },
    { id: 55, name: 'シネマサンシャイン平和島' },
    { id: 56, name: 'ユナイテッド・シネマ豊洲' },
    { id: 57, name: 'ユナイテッド・シネマ アクアシティお台場' },
    { id: 58, name: '109シネマズ木場' },
    { id: 59, name: 'T・ジョイSEIBU大泉' },
    { id: 60, name: 'ユナイテッド・シネマとしまえん' },
    { id: 61, name: 'イオンシネマ板橋' },
    { id: 62, name: 'MOVIX亀有' },
    { id: 63, name: 'TOHOシネマズ西新井' },
    { id: 64, name: 'シネマブルースタジオ' },
    { id: 65, name: '船堀シネパル' },
    { id: 66, name: 'ポレポレ東中野' },
    { id: 67, name: 'ラピュタ阿佐ヶ谷' },
    { id: 68, name: 'Morc阿佐ヶ谷' },
    { id: 69, name: 'アップリンク吉祥寺' },
    { id: 70, name: '吉祥寺オデヲン' },
    { id: 71, name: 'イオンシネマ シアタス調布' },
    { id: 72, name: 'TOHOシネマズ府中' },
    { id: 73, name: '109シネマズグランベリーパーク' },
    { id: 74, name: 'TOHOシネマズ立川立飛' },
    { id: 75, name: '立川シネマシティ' },
    { id: 76, name: '立川シネマシティ（シネマ・ツー）' },
    { id: 77, name: 'kino cinema 立川高島屋 S.C.館' },
    { id: 78, name: 'MOVIX昭島' },
    { id: 79, name: 'イオンシネマむさし村山' },
    { id: 80, name: 'TOHOシネマズ南大沢' },
    { id: 81, name: 'イオンシネマ多摩センター' },
    { id: 82, name: 'イオンシネマ日の出' },
    { id: 83, name: 'シネマネコ' }
  ]

  include ActiveHash::Associations
  has_many :movies
end